services:
  locust-exporter:
    image: containersol/locust_exporter
    container_name: locust-exporter
    ports:
      - 9646:9646
    environment:
      - LOCUST_EXPORTER_URI=http://host.docker.internal:8089
    networks:
      - metrics-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - metrics-network
    volumes:
      - grafana-storage:/var/lib/grafana




  prometheus-metrics:
    image: prom/prometheus:latest
    container_name: prometheus-metrics-exporter
    ports:
      - 9090:9090
    networks:
      - metrics-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro


networks:
  metrics-network:
    driver: bridge


volumes:
  grafana-storage:
